name: ${project.artifactId}
version: ${project.version}
author: LightMute
main: ${project.groupId}.${project.artifactId}.App
api-version: 1.14
commands:
   mariage:
     description: faire un mariage.
     usage: /mariage <message>.